services:
  pasarguard:
    image: pasarguard/panel:latest
    restart: always
    env_file: .env
    # network_mode: host
    volumes:
      - pasarguard_data:/var/lib/pasarguard
volumes:
  pasarguard_data:
