services:
  pasarguard:
    build:
      context: .
      dockerfile: Dockerfile
      
    
    restart: always
    env_file: .env
    # network_mode: host
    volumes:
      - pasarguard_data:/var/lib/pasarguard
volumes:
  pasarguard_data:
